services:
  frontend-jenkins:
    image: node:18-alpine
    container_name: ecommerce-frontend-jenkins
    restart: always
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run preview -- --host 0.0.0.0 --port 3001"
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
